src/books/urls.py
from django.urls import path
from books.views import CreateBooks, UpdateBooks, ListBooks, DeleteBooks
from books.views import DetailBooks, ListBooksManager, ListBooksSearch

app_name = "books"


urlpatterns = [
    path('create-books/', CreateBooks.as_view(), name="create"),
    path('update-books/<int:pk>', UpdateBooks.as_view(), name="update"),
    path('list-books/', ListBooks.as_view(), name="list"),
    path('delete-books/<int:pk>', DeleteBooks.as_view(), name="delete"),
    path('detail-books/<int:pk>', DetailBooks.as_view(), name="detail"),
    path('list-books-manager/', ListBooksManager.as_view(), name="list_manager"),
    path('list-books-search/', ListBooksSearch.as_view(), name="list_search"),
]

src/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from profiles.auth_views import MyLogin, MyLogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ref_books/', include('ref_books.urls', namespace="ref_books")),
    path('books/', include('books.urls', namespace="books")),
    path('', include('homepage.urls', namespace="homepage")),
    path('profiles/', include('profiles.urls', namespace="profile")),
    path('login/', MyLogin.as_view(), name="login"),
    path('logout/', MyLogout.as_view(), name="logout"),
    path('basket/', include('basket.urls', namespace="basket")),
    path('order/', include('order.urls', namespace="order")),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.urls import path
from profiles.views import CreateProfile, UpdateProfile, DetailProfile
from profiles.views import ListProfilesManager, UpdateProfileManager

app_name = "profile"


urlpatterns = [
    path('create-profile/', CreateProfile.as_view(), name="create"),
    path('update-profile/<int:pk>', UpdateProfile.as_view(), name="update"),
    path('detail-profile/<int:pk>', DetailProfile.as_view(), name="detail"),
    path('list-profiles-manager/', ListProfilesManager.as_view(), name="list_manager"),
    path('update-profile-manager/<int:pk>', UpdateProfileManager.as_view(), name="update_manager"),
]

src/ref_books/urls.py
from django.urls import path
from ref_books.views import CreateGenre, UpdateGenre, ListGenre, DeleteGenre, DetailGenre, RefBooksManager

app_name = "ref_books"


urlpatterns = [
    path('create-genre/', CreateGenre.as_view(), name="create_genre"),
    path('update-genre/<int:pk>', UpdateGenre.as_view(), name="update_genre"),
    path('list-genre/', ListGenre.as_view(), name="list_genre"),
    path('delete-genre/<int:pk>', DeleteGenre.as_view(), name="delete_genre"),
    path('detail-genre/<int:pk>', DetailGenre.as_view(), name="detail_genre"),
    path('ref_books_manager', RefBooksManager.as_view(), name="ref_books_manager"),
]

src/profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Profile(AbstractUser):
    phone_number = models.CharField(
        verbose_name="Мобильный номер телефона",
        max_length=30,
        null=True,
        blank=True
    )
    country = models.CharField(
        verbose_name="Страна",
        max_length=30,
        null=True,
        blank=True
    )
    city = models.CharField(
        verbose_name="Город",
        max_length=30,
        null=True,
        blank=True
    )
    index = models.CharField(
        verbose_name="Индекс",
        max_length=30,
        null=True,
        blank=True
    )
    adress1 = models.CharField(
        verbose_name="Адрес прописки",
        max_length=40,
        null=True,
        blank=True
    ) 
    adress2 = models.CharField(
        verbose_name="Адрес проживания",
        max_length=40,
        null=True,
        blank=True
    )
    additionally = models.TextField(
        verbose_name="Дополнительная информация",
        null=True,
        blank=True
    )

    class Meta:
        permissions = [
                    ("view_all_profiles", "Can view all profiles"),
                ]
    def __str__(self):
        return self.first_name

src/profiles/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile
from django.contrib.auth.models import Group
from django import forms

class CreateProfileForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Profile
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email', 
                                                'phone_number', 'country', 'city', 'index', 
                                                'adress1', 'adress2', 'additionally')

class UpdateProfileForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Profile
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'email', 
                                                'phone_number', 'country', 'city', 'index', 
                                                'adress1', 'adress2', 'additionally')

class UpdateProfileFormManager(forms.ModelForm):
    #groups = forms.ModelMultipleChoiceField( 
    #    queryset=Group.objects.all(),
    #    to_field_name='name',
    #    widget=forms.CheckboxSelectMultiple,
    #)
    class Meta(UserChangeForm.Meta):
        model = Profile
        fields = ('first_name', 'last_name', 'email', 
                    'phone_number', 'country', 'city', 'index', 
                    'adress1', 'adress2', 'additionally', 'is_staff', 
                    #'groups'
                )

src/profiles/views.py
from django.urls import reverse_lazy
from .models import Profile
from .forms import CreateProfileForm, UpdateProfileForm, UpdateProfileFormManager
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import ListView
from django.views.generic import DeleteView
from django.views.generic import DetailView


class CreateProfile(CreateView):
    model = Profile
    form_class = CreateProfileForm
    template_name = 'profiles/create_profile.html'
    def get_success_url(self):
        return reverse_lazy('homepage:homepage') 

class UpdateProfile(UpdateView):
    model = Profile
    form_class = UpdateProfileForm
    template_name = 'profiles/update_profile.html'
    def get_success_url(self):
        return reverse_lazy('homepage:homepage')

class DetailProfile(DetailView):
    model = Profile
    template_name = 'profiles/detail_profile.html'


class ListProfilesManager(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    permission_required = 'profiles.view_all_profiles'
    model = Profile
    template_name = 'profiles/list_profiles_manager.html'

class UpdateProfileManager(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'profiles.view_all_profiles'
    model = Profile
    form_class = UpdateProfileFormManager
    template_name = 'profiles/update_profile_manager.html'
    def get_success_url(self):
        return reverse_lazy('profile:list_manager')

src/profiles/templates/profiles/list_genre.html
{% extends "base.html" %}
{% load static %}
  {% block title %} Список жанров {% endblock title %}
  {% block main %} 
    <section class="jumbotron text-center">
      <div class="container">
      <h1>Список жанров</h1>
      </div>
    </section>
    <div class="album py-5 bg-light"> 
      <div class="container">
        <div class="row">
          {% for obj in object_list %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                    <a href="{% url 'ref_books:detail_genre' obj.pk %}"> 
                      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                        <title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"/>
                        <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ obj.name }}</text>
                      </svg>
                    </a> 
                    <div class="card-body">
                      <p class="card-text">{{ obj.description }}
                        <div class="d-flex justify-content-between align-items-center">
                          <div class="btn-group">
                            {% if 'ref_books.change_genre' and 'ref_books.delete_genre' in perms %}
                              <a href="{% url 'ref_books:update_genre' obj.pk %}"><i class="fas fa-pen"></i><br>
                              <a href="{% url 'ref_books:delete_genre' obj.pk %}"><i class="fas fa-trash"></i></a>
                            {% endif %}
                          </div>
                        </div>
                      </p>
                    </div>
              </div>
            </div>
          {% endfor %} 
        </div>
      </div>
    </div>
  {% endblock main %}

src/profiles/templates/profiles/list_profiles_manager.html
{% extends "base_manager.html" %}
{% load static %}
  {% block title %} Список всех пользователей {% endblock title %}
  {% block main_block_manager %}
    <section class="jumbotron text-center">
      <div class="container sticky-top">
        <h1 class="sticky-top">Список всех пользователей</h1><br>  
      </div>
          <div class="col bg-light py-3" align="center"> 
            <li class="list-group-item d-flex justify-content-between align-items-center ">
              <div class="col" align="center">
              </div>
            </li>
          </div>
    </section>

      <div class="col">
        <p>
          <div class="col-3">
            <button class="btn btn-primary btn-block" type="button" data-toggle="collapse" data-target="#list_profiles_manager_staff" aria-expanded="false" aria-controls="list_profiles_manager_staff">
              Список сотрудников
            </button>
          </div>
        </p>
        <div class="collapse" id="list_profiles_manager_staff">
          <div class="card card-body">
            <table class="table table-sm table-hover">
              <thead>
                <tr align="center">
                  <th scope="col" width="22%">Логин</th>
                  <th scope="col" width="22%">Имя</th>
                  <th scope="col" width="23%">email</th>
                  <th scope="col" width="23%">Дата регистрации</th>
                  <th scope="col" width="21%">Обновить</th>
                </tr>
              </thead>
              <tbody>
                {% for profile in object_list %}
                  {% if profile.is_staff and profile.is_superuser is False %}
                    <tr align="center">
                      <td>{{ profile.username }}</td>
                      <td>{{ profile.first_name }}</td>
                      <td>{{ profile.email }}</td>
                      <td>{{ profile.date_joined }}</td>
                      <td>
                        <a class="btn btn-warning btn-sm btn-block" href=" {% url 'profile:update_manager' profile.pk%} ">Посмотреть/Обновить</a>
                      </td>
                    </tr>
                  {% endif %}
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      
      <div class="col">
        <p>
          <div class="col-3">
            <button class="btn btn-primary btn-block" type="button" data-toggle="collapse" data-target="#list_profiles_manager_customers" aria-expanded="false" aria-controls="list_profiles_manager_customers">
              Список клиентов
            </button>
          </div>
        </p>
        <div class="collapse" id="list_profiles_manager_customers">
          <div class="card card-body">
            <table class="table table-sm table-hover">
              <thead>
                <tr align="center">
                  <th scope="col" width="22%">Логин</th>
                  <th scope="col" width="22%">Имя</th>
                  <th scope="col" width="23%">email</th>
                  <th scope="col" width="23%">Дата регистрации</th>
                  <th scope="col" width="21%">Обновить</th>
                </tr>
              </thead>
              <tbody>
                {% for profile in object_list %}
                  {% if profile.is_staff is False and profile.is_superuser is False %}
                    <tr align="center">
                      <td>{{ profile.username }}</td>
                      <td>{{ profile.first_name }}</td>
                      <td>{{ profile.email }}</td>
                      <td>{{ profile.date_joined }}</td>
                      <td>
                        <a class="btn btn-warning btn-sm btn-block" href=" {% url 'profile:update_manager' profile.pk%} ">Посмотреть/Обновить</a>
                      </td>
                    </tr>
                  {% endif %}
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

  {% endblock main_block_manager %}

src/profiles/templates/profiles/update_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Изменение Профиля {% endblock title %}
  {% block main %}
    <div class="row">
      <div class="col">
        
      </div>
      <div class="col-7">
        <section class="jumbotron text-center">
          <div class="container">
            <h1>Изменить Профиль</h1>
          </div>
        </section>
        <div class="album py-5 bg-light"> 
          <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-danger">Отправить</button>
          </form>
        </div>
      </div>
      <div class="col">
        
      </div>
    </div> 
  {% endblock main %}

src/profiles/templates/profiles/update_profile_manager.html
{% extends "base_manager.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Изменение Профиля {% endblock title %}
  {% block main_block_manager %}
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-7">
            <section class="jumbotron text-center">
              <div class="container">
                <h1>Изменить Профиль</h1>
              </div>
            </section>
            <div class="album py-5 bg-light"> 
              <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-danger">Отправить</button>
              </form>
            </div>
          </div>
        </div>
      </div>
  {% endblock main_block_manager %}