src/books/urls.py
from django.urls import path
from books.views import CreateBooks, UpdateBooks, ListBooks, DeleteBooks
from books.views import DetailBooks, ListBooksManager, ListBooksSearch

app_name = "books"


urlpatterns = [
    path('create-books/', CreateBooks.as_view(), name="create"),
    path('update-books/<int:pk>', UpdateBooks.as_view(), name="update"),
    path('list-books/', ListBooks.as_view(), name="list"),
    path('delete-books/<int:pk>', DeleteBooks.as_view(), name="delete"),
    path('detail-books/<int:pk>', DetailBooks.as_view(), name="detail"),
    path('list-books-manager/', ListBooksManager.as_view(), name="list_manager"),
    path('list-books-search/', ListBooksSearch.as_view(), name="list_search"),
]

src/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from profiles.auth_views import MyLogin, MyLogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ref_books/', include('ref_books.urls', namespace="ref_books")),
    path('books/', include('books.urls', namespace="books")),
    path('', include('homepage.urls', namespace="homepage")),
    path('profiles/', include('profiles.urls', namespace="profile")),
    path('login/', MyLogin.as_view(), name="login"),
    path('logout/', MyLogout.as_view(), name="logout"),
    path('basket/', include('basket.urls', namespace="basket")),
    path('order/', include('order.urls', namespace="order")),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/ref_books/urls.py
from django.urls import path
from ref_books.views import CreateGenre, UpdateGenre, ListGenre, DeleteGenre, DetailGenre, RefBooksManager

app_name = "ref_books"


urlpatterns = [
    path('create-genre/', CreateGenre.as_view(), name="create_genre"),
    path('update-genre/<int:pk>', UpdateGenre.as_view(), name="update_genre"),
    path('list-genre/', ListGenre.as_view(), name="list_genre"),
    path('delete-genre/<int:pk>', DeleteGenre.as_view(), name="delete_genre"),
    path('detail-genre/<int:pk>', DetailGenre.as_view(), name="detail_genre"),
    path('ref_books_manager', RefBooksManager.as_view(), name="ref_books_manager"),
]

src/ref_books/models.py
from django.db import models

# Create your models here.

#Чтобы изменения попали в базу данных надо сделать:
#python manage.py makemigrations - создать миграции
#python manage.py migrate - отправить миграции в базу данных
class Genre(models.Model):
    name = models.CharField(
        verbose_name="Название Жанра",
        max_length=30
    )
    description = models.TextField(
        verbose_name="Описание Жанра",
        null=True,
        blank=True
    )
    class Meta:
        permissions = [
                    ("view_all_genres", "Can view all genres"),
                ]
    def __str__(self):
        return self.name

    

src/ref_books/forms.py
from django import forms
from .models import Genre

class GenreForm(forms.ModelForm):
    class Meta:
        model = Genre
        fields = ['name', 'description']

src/ref_books/views.py
from django.urls import reverse_lazy
from .models import Genre
from .forms import GenreForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import ListView
from django.views.generic import DeleteView
from django.views.generic import DetailView
# Create your views here.

# Для CREATE
# 1 Определить метод (GET или POST)
# 2 GET - создать форму, подкинуть её в контекст, показать страницу
# 3 POST - получить данные из POST-запроса, создать объкт, сохранить его в БД
# 4 Показать "другую" страницу (сообщение об успехе)

class CreateGenre(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'ref_books.add_genre'
    model = Genre
    form_class = GenreForm
    template_name = 'ref_books/create_genre.html'
    def get_success_url(self):
        return reverse_lazy('ref_books:ref_books_manager')

class UpdateGenre(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'ref_books.change_genre'
    model = Genre
    form_class = GenreForm
    template_name = 'ref_books/update_genre.html'
    def get_success_url(self):
        return reverse_lazy('ref_books:ref_books_manager')
        #return reverse_lazy('genre:list', kwargs={'pk': self.object.pk})

class ListGenre(ListView):
    model = Genre
    template_name = 'ref_books/list_genre.html'

class DeleteGenre(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    login_url = reverse_lazy('login')
    permission_required = 'ref_books.delete_genre'
    model = Genre
    template_name = 'ref_books/delete_genre.html'
    def get_success_url(self):
        return reverse_lazy('ref_books:ref_books_manager')

class DetailGenre(DetailView):
    model = Genre
    template_name = 'ref_books/detail_genre.html'

class RefBooksManager(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    permission_required = 'ref_books.view_all_genres'
    model = Genre
    template_name = 'ref_books/ref_books_manager.html'

    def get_success_url(self):
        return reverse_lazy('ref_books:ref_books_manager')




#class Test(TemplateView):
#    template_name = 'genres/test.html'
#    
#    def get_context_data(self, **kwargs):
#        # 1. Берём родительский метод применя метода super() 
#        # 2. Добавляем своих параметров  
#        context = super().get_context_data(**kwargs)
#        context['rate'] = self.get_rate()
#        return context
#    def get_rate(self):
#        return 2.755
     

src/ref_books/templates/ref_books/create_genre.html
{% extends "base_manager.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Создание нового жанра {% endblock title %}
  {% block main_block_manager %}
      <section class="jumbotron text-center">
        <div class="container">
          <h1>Создание нового Жанра</h1>
        </div>
      </section>
      <div class="album py-5 bg-light">
        <div class="my-3 p-3 bg-white rounded shadow-sm"> 
          <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-danger">Отправить</button>
          </form>
        </div>  
      </div>
  {% endblock main_block_manager %}

src/ref_books/templates/ref_books/delete_genre.html
{% extends "base_manager.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Удаление жанра {% endblock title %}
  {% block main_block_manager %} 
    <section class="jumbotron text-center">
      <div class="container">
        <h1>Вы действительно хотите удалить Жанр: {{ object }}?</h1>
      </div>
    </section>
    <div class="album py-5 bg-light"> 
      <form action="" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Удалить</button>
      </form>
    </div>
  {% endblock main_block_manager %}

src/ref_books/templates/ref_books/detail_genre.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Детальная информация по жанру {% endblock title %}
  {% block main %} 
    <section class="jumbotron text-center">
      <div class="container">
        <h1>Полная информация по Жанру: {{ object }}?</h1>
      </div>
    </section>
    <div class="album py-5 bg-light"> 
    Coming soon
    </div>
  {% endblock main %}

src/ref_books/templates/ref_books/list_genre.html
{% extends "base.html" %}
{% load static %}
  {% block title %} Список жанров {% endblock title %}
  {% block main %}
    <div class="row">
      <div class="col">

      </div>
      <div class="col-7">
        <section class="jumbotron text-center">
          <div class="container">
          <h1>Список жанров</h1>
          </div>
        </section>
        <div class="album py-5 bg-light"> 
          <div class="container">
            <div class="row">
              {% for obj in object_list %}
                <div class="col-md-4">
                  <div class="card mb-4 shadow-sm">
                        <a href="{% url 'ref_books:detail_genre' obj.pk %}"> 
                          <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                            <title>Placeholder</title>
                            <rect width="100%" height="100%" fill="#55595c"/>
                            <text x="50%" y="50%" fill="#eceeef" dy=".3em">{{ obj.name }}</text>
                          </svg>
                        </a> 
                        <div class="card-body">
                          <p class="card-text">{{ obj.description }}
                            <div class="d-flex justify-content-between align-items-center">
                              <div class="btn-group">
                                {% if 'ref_books.change_genre' and 'ref_books.delete_genre' in perms %}
                                  <a href="{% url 'ref_books:update_genre' obj.pk %}"><i class="fas fa-pen"></i><br>
                                  <a href="{% url 'ref_books:delete_genre' obj.pk %}"><i class="fas fa-trash"></i></a>
                                {% endif %}
                              </div>
                            </div>
                          </p>
                        </div>
                  </div>
                </div>
              {% endfor %} 
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        
      </div>
    </div>
  {% endblock main %}

src/ref_books/templates/ref_books/ref_books_manager.html
{% extends "base_manager.html" %}
{% load static %}
  {% block title %} Справочники {% endblock title %}
  {% block main_block_manager %}
    <section class="jumbotron text-center">
      <div class="container sticky-top">
        <h1 class="sticky-top">Справочники</h1><br>  
      </div>
    </section>
    <div class="container">
      <div class="col">
        <p>
          <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#list_genre_manager" aria-expanded="false" aria-controls="list_genre_manager">
            Список Жанров
          </button>
          <a class="btn btn-success" type="button" href="{% url 'ref_books:create_genre' %}">
            Создать Жанр
          </a>
        </p>
        <div class="collapse" id="list_genre_manager">
          <div class="card card-body">
            <table class="table table-sm table-hover">
              <thead>
                <tr align="center">
                  <th scope="col" width="20%">Название Жанра</th>
                  <th scope="col" width="60%">Описание Жанра</th>
                  <th scope="col" width="10%">Обновить</th>
                  <th scope="col" width="10%">Удалить</th>
                </tr>
              </thead>
              <tbody>
                {% for genre in object_list %}
                    <tr align="center">
                      <td>{{ genre.name }}</td>
                      <td>{{ genre.description }}</td>
                      <td>
                        <a class="btn btn-warning btn-sm btn-block" href=" {% url 'ref_books:update_genre' genre.pk%} ">Обновить</a>
                      </td>
                      <td>
                        <a class="btn btn-danger btn-sm btn-block" href=" {% url 'ref_books:delete_genre' genre.pk%} ">Удалить</a>
                      </td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>
  {% endblock main_block_manager %}

src/ref_books/templates/ref_books/update_genre.html
{% extends "base_manager.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Изменение Жанра {% endblock title %}
  {% block main_block_manager %} 
    <section class="jumbotron text-center">
      <div class="container">
        <h1>Изменить Жанр</h1>
      </div>
    </section>
    <div class="album py-5 bg-light"> 
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-danger">Отправить</button>
      </form>
    </div>
  {% endblock main_block_manager %}