src/books/urls.py
from django.urls import path
from books.views import CreateBooks, UpdateBooks, ListBooks, DeleteBooks
from books.views import DetailBooks, ListBooksManager, ListBooksSearch

app_name = "books"


urlpatterns = [
    path('create-books/', CreateBooks.as_view(), name="create"),
    path('update-books/<int:pk>', UpdateBooks.as_view(), name="update"),
    path('list-books/', ListBooks.as_view(), name="list"),
    path('delete-books/<int:pk>', DeleteBooks.as_view(), name="delete"),
    path('detail-books/<int:pk>', DetailBooks.as_view(), name="detail"),
    path('list-books-manager/', ListBooksManager.as_view(), name="list_manager"),
    path('list-books-search/', ListBooksSearch.as_view(), name="list_search"),
]

src/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from profiles.auth_views import MyLogin, MyLogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ref_books/', include('ref_books.urls', namespace="ref_books")),
    path('books/', include('books.urls', namespace="books")),
    path('', include('homepage.urls', namespace="homepage")),
    path('profiles/', include('profiles.urls', namespace="profile")),
    path('login/', MyLogin.as_view(), name="login"),
    path('logout/', MyLogout.as_view(), name="logout"),
    path('basket/', include('basket.urls', namespace="basket")),
    path('order/', include('order.urls', namespace="order")),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/homepage/urls.py
from django.urls import path
from homepage.views import HomePage

app_name = "homepage"


urlpatterns = [
    path('', HomePage.as_view(), name="homepage"),
]

src/ref_books/urls.py
from django.urls import path
from ref_books.views import CreateGenre, UpdateGenre, ListGenre, DeleteGenre, DetailGenre, RefBooksManager

app_name = "ref_books"


urlpatterns = [
    path('create-genre/', CreateGenre.as_view(), name="create_genre"),
    path('update-genre/<int:pk>', UpdateGenre.as_view(), name="update_genre"),
    path('list-genre/', ListGenre.as_view(), name="list_genre"),
    path('delete-genre/<int:pk>', DeleteGenre.as_view(), name="delete_genre"),
    path('detail-genre/<int:pk>', DetailGenre.as_view(), name="detail_genre"),
    path('ref_books_manager', RefBooksManager.as_view(), name="ref_books_manager"),
]

src/templates/base.html
{%load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>{% block title %} Unknown Title {% endblock title %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

        <!-- Bootstrap core CSS -->

        <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include "header.html" %}
    <div class="mt-5 pt-1">
      <main role="main" >
        {% block main %} Unknown Body {% endblock main %}
      </main>
    </div>
    {% include "footer.html" %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>





{% comment %} 

          <div class="row">
            <div class="col">
              1 из 3
            </div>
            <div class="col-7">
              Unknown Body
            </div>
            <div class="col">
              3 из 3
            </div>
          </div> 
          
{% endcomment %}

src/templates/base_login.html
{%load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>{% block title %} Unknown Title {% endblock title %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

        <!-- Bootstrap core CSS -->

        <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>
  <body>
    <main role="main" class="container">
      {% block main %} Unknown Body {% endblock main %}
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/base_manager.html
{%load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>{% block title %} Unknown Title {% endblock title %}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/album/">

        <!-- Bootstrap core CSS -->

        <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon.ico">
    <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    
      table {
          table-layout: fixed;
          width:100%
      }

      td {
          word-wrap:break-word;
      }

    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include "header.html" %}
    <div class="container-fluid">
      <div class="row ">
        {% include "left_block_manager.html" %}
        <div class="col-9">
          <main role="main">
            {% block main_block_manager %} Unknown Body {% endblock main_block_manager %}
          </main>
        </div>
        {% include "right_block_manager.html" %} 
      </div>
    </div>
    {% include "footer.html" %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/footer.html
<footer class="text-muted">
    <div class="container">
    <p class="float-right">
        <a href="#">Back to top</a>
    </p>
    <p>Album example is &copy; Bootstrap</p>
    </div>
</footer>

src/templates/header.html
{% comment %} <nav class="navbar p-0 flex-md-nowrap navbar-dark bg-dark sticky-top"> {% endcomment %}
<nav class="navbar navbar-expand-md flex-md-nowrap navbar-dark bg-dark sticky-top">  
    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
        <div class="col">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'homepage:homepage' %}">На главную страницу</a>
            </li>
              <a class="nav-link" href="{% url 'books:list' %}">Книги</a>
              <a class="nav-link" href="{% url 'ref_books:list_genre' %}">Жанры</a>
          </ul>
        </div>
        <div class="d-flex justify-content-end">
          <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'profile:update' user.pk %}"> Пользователь: {{ user.username }} </a>
              </li>                    
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Профиль</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                  <a class="dropdown-item" href="{% url 'profile:update' user.pk %}">Данные пользователя</a>
                  <a class="dropdown-item" href="{% url 'basket:list'%}">Корзина</a>
                  <a class="dropdown-item" href="{% url 'order:list'%}">Заказы</a>
                  {% if user.is_staff %}
                    <a class="dropdown-item" href="{% url 'order:list_manager'%}">Менеджер</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                </div>
              </li>             
            {% else %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Войти</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                  <a class="dropdown-item" href="{% url 'profile:create'%}">Регистрация</a>
                  <a class="dropdown-item" href="{% url 'basket:list'%}">Корзина</a>
                  <a class="dropdown-item" href="">Заказы</a>
                  <a class="dropdown-item" href="{% url 'login' %}">Войти</a>
                </div>
              </li>                  
            {% endif %}
            <form class="form-inline my-2 my-lg-0" action="{% url 'books:list_search' %}" method="get">
              {% csrf_token %}
              <input name="q" class="form-control mr-sm-2" type="text" placeholder="Поиск книги" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>               
          </ul>
        </div>
    </div>
</nav>

src/templates/left_block_manager.html
<div class="col bg-light">
  <nav class="col-md-2 d-none d-md-block  sidebar ">
    <div class="sidebar-sticky position-fixed">
      <ul class="nav flex-column">
        <li class="nav-item">
          <a class="nav-link active text-dark font-weight-bold" href="{% url 'order:list_manager'%}">
            <i class="far fa-file-alt fa-fw"></i>
            Заказы
          </a> 
        </li>
        <li class="nav-item">
          <a class="nav-link active text-dark font-weight-bold" href="{% url 'basket:list_manager'%}">
            <i class="fas fa-shopping-basket fa-fw" ></i>
            Корзины
          </a> 
        </li>
        <li class="nav-item">
          <a class="nav-link active text-dark font-weight-bold " href="{% url 'books:list_manager'%}">
            <i class="fas fa-book fa-fw"></i>
            Книги
          </a> 
        </li>
        <li class="nav-item">
          <a class="nav-link active text-dark font-weight-bold" href="{% url 'ref_books:ref_books_manager'%}">
            <i class="fas fa-list fa-fw"></i>
            Справочники
          </a> 
        </li>
        <li class="nav-item">
          <a class="nav-link active text-dark font-weight-bold" href="{% url 'profile:list_manager'%}">
            <i class="fas fa-user fa-fw"></i>
            Пользователи
          </a> 
        </li>
      </ul>
    </div>
  </nav>
</div>

src/templates/right_block_manager.html
<div class="col bg-light">
  <p>{{ usd }}</p>
  <p>{{ eur }}</p>
  <p>{{ rub }}</p>
</div>