src/basket/urls.py
from django.urls import path
from basket.views import AddBookToBasket, ListBooksInBasket, DeleteBooksFromBasket, ListBasketsManager, DeatailBasketsManager

app_name = "basket"


urlpatterns = [
    path('add/', AddBookToBasket.as_view(), name="add"),
    path('list/', ListBooksInBasket.as_view(), name="list"),
    path('delete/<int:pk>', DeleteBooksFromBasket.as_view(), name="delete"),
    path('list_manager/', ListBasketsManager.as_view(), name="list_manager"),
    path('detail_manager/<int:pk>', DeatailBasketsManager.as_view(), name="detail_manager"),
]

src/books/urls.py
from django.urls import path
from books.views import CreateBooks, UpdateBooks, ListBooks, DeleteBooks
from books.views import DetailBooks, ListBooksManager, ListBooksSearch

app_name = "books"


urlpatterns = [
    path('create-books/', CreateBooks.as_view(), name="create"),
    path('update-books/<int:pk>', UpdateBooks.as_view(), name="update"),
    path('list-books/', ListBooks.as_view(), name="list"),
    path('delete-books/<int:pk>', DeleteBooks.as_view(), name="delete"),
    path('detail-books/<int:pk>', DetailBooks.as_view(), name="detail"),
    path('list-books-manager/', ListBooksManager.as_view(), name="list_manager"),
    path('list-books-search/', ListBooksSearch.as_view(), name="list_search"),
]

src/first_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from profiles.auth_views import MyLogin, MyLogout

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ref_books/', include('ref_books.urls', namespace="ref_books")),
    path('books/', include('books.urls', namespace="books")),
    path('', include('homepage.urls', namespace="homepage")),
    path('profiles/', include('profiles.urls', namespace="profile")),
    path('login/', MyLogin.as_view(), name="login"),
    path('logout/', MyLogout.as_view(), name="logout"),
    path('basket/', include('basket.urls', namespace="basket")),
    path('order/', include('order.urls', namespace="order")),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/books/models.py
from django.db import models
from ref_books.models import Genre
# Create your models here.

#Чтобы изменения попали в базу данных надо сделать:
#python manage.py makemigrations - создать миграции
#python manage.py migrate - отправить миграции в базу данных
class Books(models.Model):
    name = models.CharField(
        verbose_name="Название книги",
        max_length=30
    )
    cover_photo = models.ImageField(
        verbose_name="Фото на обложке",
        upload_to="books-photo",
        null=True,
        blank=True
    )
    price = models.DecimalField(
        verbose_name="Цена (BYN)",
        max_digits= 20,
        decimal_places= 2
    )
    author = models.CharField(
        verbose_name="Автор",
        max_length=30
    )
    series = models.CharField(
        verbose_name="Серия",
        max_length=30
    )
    genre = models.ForeignKey(
        Genre,
        on_delete=models.CASCADE,
        verbose_name="Жанр",
        null=True,
        blank=True
    )
    publishing_year = models.DateField(
        verbose_name="Год издания",
    )
    pages = models.IntegerField(
        verbose_name="Количество страниц",
    )
    binding = models.CharField(
        verbose_name="Переплёт",
        max_length=30
    )
    book_format = models.CharField(
        verbose_name="Формат книги",
        max_length=30
    )
    isbn = models.CharField(
        verbose_name="ISBN",
        max_length=30
    ) 
    weight = models.IntegerField(
        verbose_name="Вес книги (в граммах)",
    )
    age = models.IntegerField(
        verbose_name="Возрастные ограничения",
    )
    publishing = models.CharField(
        verbose_name="Издательство",
        max_length=30
    ) 
    in_stock = models.IntegerField(
        verbose_name="Количество книг в наличии",
    )
    active = models.BooleanField(
        verbose_name="Доступен для заказа"
    )
    rating = models.IntegerField(
        verbose_name="Рейтинг",
    )
    catalog_date = models.DateTimeField(
        verbose_name="Дата внесения в каталог",
        auto_now=False,
        auto_now_add=True
    )
    card_change_date = models.DateTimeField(
        verbose_name="Дата последнего изменения карточки",
        auto_now=True,
        auto_now_add=False
    )

    class Meta:
        permissions = [
                    ("view_all_books", "Can view all books"),
                ]



    def __str__(self):
        return self.name

src/books/forms.py
from django import forms
from .models import Books

class BooksForm(forms.ModelForm):
    
    class Meta:
        model = Books
        fields = ['name', 'cover_photo', 'price', 'author', 'series', 'genre', 'publishing_year',
                  'pages', 'binding', 'book_format', 'isbn', 'weight', 'age', 'publishing', 'in_stock', 'active',
                  'rating']

src/books/views.py
from django.urls import reverse_lazy
from .models import Books
from .forms import BooksForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import ListView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.db.models import Q

# Для CREATE
# 1 Определить метод (GET или POST)
# 2 GET - создать форму, подкинуть её в контекст, показать страницу
# 3 POST - получить данные из POST-запроса, создать объкт, сохранить его в БД
# 4 Показать "другую" страницу (сообщение об успехе)

class CreateBooks(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    login_url = reverse_lazy('login')
    permission_required = 'books.add_books'
    model = Books
    form_class = BooksForm
    template_name = 'books/create_books.html'
    def get_success_url(self):
        return reverse_lazy('books:list_manager')


class UpdateBooks(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    login_url = reverse_lazy('login')
    permission_required = 'books.add_books'
    model = Books
    form_class = BooksForm
    template_name = 'books/update_books.html'
    def get_success_url(self):
        return reverse_lazy('books:list_manager')

class ListBooks(ListView):
    model = Books
    template_name = 'books/list_books.html'

class DeleteBooks(PermissionRequiredMixin, DeleteView):
    permission_required = 'books.add_books'
    model = Books
    template_name = 'books/delete_books.html'
    def get_success_url(self):
        return reverse_lazy('books:list_manager')

class DetailBooks(DetailView):
    model = Books
    template_name = 'books/detail_books.html'

class ListBooksManager(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    login_url = reverse_lazy('login')
    permission_required = 'books.view_all_books'
    model = Books
    template_name = 'books/list_books_manager.html'
    ordering = ['-catalog_date',]

class ListBooksSearch(ListView):
    model = Books
    template_name = 'books/list_books.html'

    def get_queryset(self):
        books = self.request.GET.get('q')
        object_list = Books.objects.filter(
            #Поиск без учёта верхнего регистра не работает для русских букв
            Q(name__icontains=books) | Q(author__icontains=books)
        )
        return object_list

     

src/books/templates/books/create_books.html
{% extends "base_manager.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Создание новой книги {% endblock title %}
  {% block main_block_manager %}
      <section class="jumbotron text-center">
        <div class="container">
          <h1>Создание новой книги</h1>
        </div>
      </section>
      <div class="container">
        <div class="album py-5 bg-light">
          <div class="my-3 p-3 bg-white rounded shadow-sm"> 
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form|crispy }}
              <button type="submit" class="btn btn-danger">Отправить</button>
            </form>
          </div>
        </div>
      </div>  
  {% endblock main_block_manager %}

src/books/templates/books/delete_books.html
{% extends "base_manager.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Удаление книги {% endblock title %}
  {% block main_block_manager %}
      <div class="container">
        <section class="jumbotron text-center">
          <div class="container">
            <h1>Вы действительно хотите удалить книгу: {{ object }}?</h1>
          </div>
        </section>
        <div class="album py-5 bg-light"> 
          <form action="" method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Подтвердить</button>
          </form>
        </div>
      </div>
  {% endblock main_block_manager %}

src/books/templates/books/detail_books.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Карточка книги {% endblock title %}
  {% block main %}
    <div class="row">
      <div class="col">
        
      </div>
      <div class="col-7">
        <div class="container">
          <div class="row">
            <div class="col-sm">
              {% if object.cover_photo %}
                <p><img src="{{ object.cover_photo.url }}" class="card-img-top" alt="..."></p>
              {% else %}
                <p></p>
              {% endif %}
            </div>
            <div class="col-sm">
              <ul class="list-group">
                <li class="list-group-item">Название книги</li>
                <li class="list-group-item">Цена (BYN)</li>
                <li class="list-group-item">Автор</li>
                <li class="list-group-item">Серия</li>
                <li class="list-group-item">Жанр</li>
                <li class="list-group-item">Год издания</li>
                <li class="list-group-item">Количество страниц</li>
                <li class="list-group-item">Переплёт</li>
                <li class="list-group-item">Формат книги</li>
                <li class="list-group-item">ISBN</li>
                <li class="list-group-item">Вес книги (в граммах)</li>
                <li class="list-group-item">Возрастные ограничения</li>
                <li class="list-group-item">Издательство</li>
                <li class="list-group-item">Количество книг в наличии</li>
                <li class="list-group-item">Доступен для заказа</li>
                <li class="list-group-item">Рейтинг</li>
                <li class="list-group-item">Дата внесения в каталог</li>
                <li class="list-group-item">Дата последнего изменения карточки</li>
              </ul>        
            </div>
            <div class="col-sm">
              <ul class="list-group">
                <li class="list-group-item">{{object.name}}</li>
                <li class="list-group-item">{{object.price}}</li>
                <li class="list-group-item">{{object.author}}</li>
                <li class="list-group-item">{{object.series}}</li>
                <li class="list-group-item">{{object.genre}}</li>
                <li class="list-group-item">{{object.publishing_year}}</li>
                <li class="list-group-item">{{object.pages}}</li>
                <li class="list-group-item">{{object.binding}}</li>
                <li class="list-group-item">{{object.book_format}}</li>
                <li class="list-group-item">{{object.isbn}}</li>
                <li class="list-group-item">{{object.weight}}</li>
                <li class="list-group-item">{{object.age}}</li>
                <li class="list-group-item">{{object.publishing}}</li>
                <li class="list-group-item">{{object.in_stock}}</li>
                <li class="list-group-item">{{object.active}}</li>
                <li class="list-group-item">{{object.rating}}</li>
                <li class="list-group-item">{{object.catalog_date}}</li>
                <li class="list-group-item">{{object.card_change_date}}</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        
      </div>
    </div> 
  {% endblock main %}

src/books/templates/books/list_books.html
{% extends "base.html" %}
{% load static %}
  {% block title %} Список книг {% endblock title %}
  {% block main %}
    <div class="row">
      <div class="col">
        
      </div>
      <div class="col-8">
        <section class="jumbotron text-center">
          <div class="container">
          <h1>Список книг</h1>
          </div>
        </section> 
        <div class="album py-5 bg-light"> 
          <div class="container">
            <div class="row">
              {% for obj in object_list %}
                <div class="col-md-4">
                  <div class="card mb-4 shadow-sm">
                        <a href="{% url 'books:detail' obj.pk %}"> 
                          {% if obj.cover_photo %}
                            <p><img src="{{ obj.cover_photo.url }}" width="150" height="200"></p>
                          {% else %}
                            <p></p>
                          {% endif %}
                        </a> 
                        <div class="card-body">
                          <p class="card-text">
                            <p>{{ obj.name }}</p>
                            <p>{{ obj.author }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                              <div class="btn-group">
                                  <a href="{% url 'basket:add'%}?book_pk={{ obj.pk }}"><i class="fas fa-shopping-basket"></i></a><br>
                              </div>
                              <small class="text-muted">{{ obj.card_change_date }}</small>
                            </div>
                          </p>
                        </div>
                  </div>
                </div>
              {% endfor %} 
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        
      </div>
    </div>
  {% endblock main %}

src/books/templates/books/list_books_manager.html
{% extends "base_manager.html" %}
{% load static %}
  {% block title %} Список всех книг {% endblock title %}
  {% block main_block_manager %}
    <section class="jumbotron text-center">
      <div class="container sticky-top">
        <h1 class="sticky-top">Список всех Книг</h1><br>  
      </div>

          <div class="col bg-light py-3" align="center"> 
            <li class="list-group-item d-flex justify-content-between align-items-center ">
              <div class="col" align="center">
              <a class="btn btn-success btn-sm" href="{% url 'books:create' %}">Создать</a>
              </div>
            </li>
          </div>



    </section>
      <table class="table table-sm table-hover">
        <thead>
          <tr align="center">
            <th scope="col" width="5%">ID Книги</th>
            <th scope="col" width="9%">Обложка</th>
            <th scope="col" width="13%">Название книги</th>
            <th scope="col" width="11%">Автор</th>
            <th scope="col" width="6%">Цена</th>
            <th scope="col" width="9%">Доступен для заказа</th>
            <th scope="col" width="11%">Создано</th>
            <th scope="col" width="12%">Обновлено</th>
            <th scope="col" width="8%">Детали</th>
            <th scope="col" width="8%">Обновить</th>
            <th scope="col" width="8%">Удалить</th>
          </tr>
        </thead>
        <tbody>
          {% for book in object_list %}
              <tr align="center">
                <th scope="row">{{ book.pk }}</th>
                <td>
                  {% if book.cover_photo %}
                    <img src="{{ book.cover_photo.url }}" width="50%">
                  {% else %}
                    
                  {% endif %}
                </td>
                <td>{{ book.name }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.price }}</td>
                {% if book.active == True %}
                <td align="center"><span class="badge badge-success badge-pill">Доступен</span></td>
                {% else %}
                <td align="center"><span class="badge badge-danger badge-pill">Не доступен</span></td>
                {% endif %}
                <td>{{ book.catalog_date }}</td>
                <td>{{ book.card_change_date }}</td>
                <td>
                  <a class="btn btn-info btn-sm btn-block" href=" {% url 'books:detail' book.pk%}">Посмотреть</a>
                </td>
                <td>
                  <a class="btn btn-warning btn-sm btn-block" href=" {% url 'books:update' book.pk%}">Обновить</a>
                </td>
                <td>
                  <a class="btn btn-danger btn-sm btn-block" href=" {% url 'books:delete' book.pk%}">Удалить</a>
                </td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
  {% endblock main_block_manager %}

src/books/templates/books/update_books.html
{% extends "base_manager.html" %}
{% load crispy_forms_tags %}
{% load static %}
  {% block title %} Редактирование книги {% endblock title %}
  {% block main_block_manager %}
      <div class="container">
        <section class="jumbotron text-center">
          <div class="container">
            <h1>Редактирование книги: "{{object.name}}"</h1>
          </div>
        </section>
        <div class="album py-5 bg-light"> 
          <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-danger">Отправить</button>
          </form>
        </div>
      </div>
  {% endblock main_block_manager %}